Embedded audio subtitles support
Stremio/react-native-vlc2 pull request #4
Opened 2020-06-04 14:30 UTC by TRtomasz

Add support for switching embeded subtitles and audio tracks

2020-06-04 14:33 UTC, Ivshti approved these changes

2020-06-09 10:58 UTC, nklhtv requested changes
use final where it is needed
dont use `embedded` word in this library
use code reformat tool: `if(` must be like `if (`

2020-06-09 10:58 UTC, nklhrstv commented on vlcVideo.android.js
> +    onEmbeddedSubtitlesAvailable: PropTypes.func,
rename to onSubtitlesTracksChanged

2020-06-09 10:58 UTC, nklhrstv commented on vlcVideo.android.js
> +    onEmbeddedAudioAvailable: PropTypes.func
rename to onAudioTracksChanged

2020-06-09 10:58 UTC, nklhrstv commented on vlcVideo.android.js
> +    audio = (index) => {
rename to setAudioTrack

2020-06-09 10:58 UTC, nklhrstv commented on vlcVideo.android.js
> +    spu = (index) => {
rename to setSubtitlesTrack

2020-06-09 10:58 UTC, nklhrstv commented on android/src/main/java/com/stellarscript/vlcvideo/VLCVideoView.java
> +    public boolean setSpuDelay(long delay) {
remove this function

2020-06-09 10:58 UTC, nklhrstv commented on android/src/main/java/com/stellarscript/vlcvideo/VLCVideoView.java
> +    public TrackDescription [] getSpuTracks() {
remove this function

2020-06-09 10:58 UTC, nklhrstv commented on android/src/main/java/com/stellarscript/vlcvideo/VLCVideoProps.java
>      static final int SEEK_COMMAND_TIME_ARGUMENT_INDEX = 0;
remove those 2 constants. no need of them. hardcode `0` where it is needed. its allways 0

2020-06-09 10:58 UTC, nklhrstv commented on android/src/main/java/com/stellarscript/vlcvideo/VLCVideoEventEmitter.java
> +    void emitOnEmbeddedSubtitlesAvailable() {
use subtitlesTracks argument

2020-06-09 10:58 UTC, nklhrstv commented on android/src/main/java/com/stellarscript/vlcvideo/VLCVideoEventEmitter.java
> +    void emitOnEmbeddedAudioAvailable() {
use audioTracks argument

2020-06-29 12:01 UTC, nklhtv approved these changes

2020-06-29 15:02 UTC, merged